### ISSUE TITLE
Beacon/Recall skill permission error

### ISSUE THREAD

**Issue by Rickyling97** [navett52/Argonauts#6]
When attempting to use the Recall skill/left clicking with a beacon item in hand, it throws an error.
It will then continue on (sending a message, going through a cooldown) but won't actually teleport me.

It seems there is a conflict with both the WorldGuard and Multiverse plugin.

Error log:
https://pastebin.com/rz5m5DtB

**Comment by navett52** [comment]
I completely forgot to do a check to see if a home point was ever actually set before trying to use the ability. This will be easily fixed.

**Comment by navett52** [comment]
Completely got rid of any skills in the plugin so you shouldn't have to worry about the return icon anymore
